title:             Permaban Blog
email:             ericwp97@gmail.com
description:       Just A Gaming Blog :)
author:            Eric Williams
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
