title:              Laboratory for information and Control Systems
email:              hanlic@kaist.ac.kr
description:        정보 및 시스템 제어 연구실
author:             LiCS
baseurl:            "/lics"
url:                "https://damanikjosh.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
