title:              Data Science Blog
email:              katetrangtran@gmail.com
description:        My journey into Deep Learning practices
author:             Kate Tran
baseurl:            ""
url:                "https://hiikate.github.io"

# Social Profiles
twitter_username:   hiikatia
github_username:    hiikate
facebook_username:  katetrangtran
instagram_username:  
linkedin_username:  katetrangtran

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
