# Site settings
title: Fields of View
header-img: img/home-bg.jpg
email: info@fieldsofview.in
description: "Fields of View - Games, Simulations"
baseurl: ""
url: "http://fieldsofview.github.io"
twitter_username: fovlabs
github_username:  fieldsofview
facebook_username:  fovbangalore
linkedin_username: fields-of-view

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]  
gems: [jekyll-paginate, jekyll-sitemap]
