title:             가메
email:             wndud9678@gmail.com
description:       Study Game Programming With UnrealEngine4
author:            Kim Ju-Yeong, ReDvGaMe
baseurl:           /
url:               "http://redvgame.github.io"
search:            true # 사이트 우측 상단 검색 활성화
search_full_content: # 제목이 아닌 내용까지도 검색할 것인지에 대한 설정 기본 false

# Social Profiles
twitter_username:  
github_username:   ReDvGaMe
facebook_username: jooyoung.kim.7967
youtube_username:  UC5uEFT4zZStG3-X_hiIppiA
email:             wndud9678@gmail.com
discord_serverurl: HCTg5ef
twitch_username:   id9678


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
# Other settings
show_drafts:       false
category_dir: category/
tag_dir: tag/
