title:              Automation with Node.js
email:              melishkevich.gala@gmail.com
description:        Tips & tricks of routine automation
author:             Start Bootstrap
baseurl:            ""
url:                "https://halynamelishkevich.github.io/HalynaMelishkevych.github.io/"

# Social Profiles
github_username:    halynamelishkevich
facebook_username:  Halya Melishkevych
instagram_username: h.melishkevych
linkedin_username:  halyna-melishkevich

# Analytics
google_analytics:   G-E5HDPN42XP

# Build settings
markdown:           kramdown
highlighter:        rouge
permalink:          pretty
paginate:           5
exclude:            ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

gems:               [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]
