title:             Hsuan-lin Her
email:             b101102109@tmu.edu.tw
description:       Molecules, Sequences, Diseases.
author:            Hsuan-lin Her
baseurl:           ""
url:               "algaebrown.github.io"

# Social Profiles
twitter_username:  hermuba
github_username:   algaebrown
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: charleneher
