title:              Data Science
email:              Brett.Neubeck@gmail.com.com
description:        Data Science & Ml Projects
author:             Brett Neubeck
baseurl:            #"/startbootstrap-clean-blog-jekyll"
url:                "https://brettso.github.io"

# Social Profiles
twitter_username:  
github_username:   brettso
facebook_username:  
instagram_username:  
linkedin_username:  brett-neubeck

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
