# Site settings
title: Never Bored
header-img: img/home-bg.jpg
email: nick.vogt94@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Nicholas Vogt's Personal Blog"
baseurl: ""
url: "http://nicholas-vogt.github.io"
twitter_username: nick_vogt94
github_username:  nicholas-vogt
facebook_username:  _
email_username:  nick.vogt94@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
