title:              Conor Olive's Blog
email:              conor@conorolive.com
description:        My personal blog
author:             Conor Olive
baseurl:            "/"
url:                "https://blog.conorolive.com"

# Social Profiles
github_username:    tortotubus

# Add your google-analytics ID here to activate google analytics
google_analytics:   #UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
