title:              Than Than Swe
email:              thanthanswe124509@gmail.com
description:        
author:             Than Than Swe
baseurl:            "/thanthanswe-github.io"
url:                ""

# Social Profiles
twitter_username:   ThanThanSwe7
github_username:    thanthanswe-github
linkedin_username:  than-than-swe-0a52a216a/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 


  