# Site settings
title: 360 Thrill
header-img: img/home-bg.jpg
email: allandx@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://360thrill.com"
twitter_username: 360thrill
github_username:
facebook_username:  360thrill

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
