title:              bakemyday
email:              leekyounghee@kakao.com
description:        bakemyday : 2018년에 만들어낸 문구인데, 그때는 내가 도자기 계속 배울 줄 알았지.. 
author:             leekyounghee
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://leekyounghee.github.io/bakemyday"

# Social Profiles
twitter_username:   
github_username:    leekyounghee
facebook_username:  
instagram_username:  leekyounghee
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
