title:              testing of hosting github pages
email:              pkj.bhatt@yahoo.com
description:        A Blog Theme testing of hosting
author:             Pankaj Bhatt
baseurl:            ""
url:                "https://test.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:  djlksjdalksdjsaldjsaldjsalddlkas

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
