title:             Manjil Saikia
email:             manjil@gonitsora.com
description:       Personal Homepage
author:            Manjil Saikia
baseurl:           "/"
url:               "http://manjilsaikia.github.io"

# Social Profiles
twitter_username:  ManjilPSaikia
github_username:   ManjilSaikia
facebook_username: manjilps

# Build settings
permalink: pretty
markdown:          kramdown
paginate:          50
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
