title:             Jason Lim
email:             jasonjklim@gmail.com
description:       Data Analyst * Data Scientist
author:            Jason Lim
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://jasonjklim.github.io"

# Social Profiles
github_username:   jasonjklim
facebook_username: jasonjklim

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
