title:             Hello World!
email:             ha_x3@naver.com
description:       '?'
author:            hax3
baseurl:           "/"
url:               "http://hax3.github.io"

# Social Profiles
twitter_username:  -
github_username:   hax3
facebook_username: -

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
