title:             KDL's blog
email:             keur.plkar@gmail.com
description:       Sharing experience of buidling deep learing models, side projects and kaggle competitions
author:            Keyur Paralkar
baseurl:           ""
url:               "http://keyurparalkar.github.io"

# Social Profiles
twitter_username:  keurplkar
github_username:   keyurparalkar
facebook_username: keyur.paralkar

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
