# Site settings
title: Will Green
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Pirate, Philosopher, Storyteller"
baseurl: "/aesopist.github/io"
url: "https://willgreen.met"
twitter_username: williamgreen
github_username:  aesopist
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
