title:              "Corner of Eden"
email:              "yx2516@uw.edu"
description:        ""
baseurl:            ""
author:             "Yidan (Eden) Xu"
url:                "https://edenx.github.io"
github_username:    "edenx"

# Build settings
timezone:           "US/Seattle"
markdown:           "kramdown"
paginate:           10
paginate_path:      "/posts/page:num/"
highlighter:        "rouge"
permalink:          "pretty"
exclude:            ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
mathjax_url: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"
