title:             Clean Blog
email:             saulrodrigueit+BLOG@gmail.com
description:       A Blog about Ops and sometimes Dev
author:            Saul Rodriguez Alvarez
baseurl:           "/blog"
url:               "http://saul-r.github.io"

# Social Profiles
witter_username:  SBootstrap
github_username:   Saul-R
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

