title:              AnSa Blog
email:              ansaslu87@gmail.com
description:        Temas de ciberseguridad en general
author:             AnSa
baseurl:            /AnSa
url:                https://AnSa.github.io

# Social Profiles
twitter_username:   AnSa_1_
github_username:    AnSa-1
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      /posts/page:num/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
