# Site settings
title: Agent of Entropy
header-img: img/home-bg.jpg
email: decal@uw.edu
description: "Richard Decal's personal website."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
github_username:  isomerase


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
