title:              BlogMate
email:              mirzabeyliler@gmail.com
description:        Blog sayfama hoş geldiniz! Blogumda kendi fikirlerimi, hobilerimi yazıya dökücem.Umarım beğenirsiniz...
author:             Yusif Mirzəbəyli
baseurl:            ""
url:                "https://blogmate.github.io"

# Social Profiles
twitter_username:   nearfight0
github_username:    nearfight0
facebook_username: 
instagram_username:  _https.yusif
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
