title:              Clean Blog
email:              jdk12987@naver.com
description:        A Blog Theme by Start Bootstrap
author:             jongwonkim-1997
baseurl:            ""
url:                "https://jongwonkim-1997.github.io"

# Social Profiles
twitter_username:   
github_username:    jongwonkim-1997
facebook_username:  
instagram_username: abcd1234ing 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
