# Site settings
title: Javacafe Blog
header-img: img/home-bg.jpg
email: 
copyright_name: Javacafe
description: "Javacafe Tech Blog"
baseurl: "/official-blog"
url: "http://yourdomain.com"
twitter_username: 
github_username:  JAVACAFE_STUDY
facebook_username:  https://www.facebook.com/groups/javacafe/
email_username:  

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
