# Site settings
title: Security In Obscurity
email: xorrior@gmail.com
description: "Various information security topics among other things"
baseurl: ""
url: ""
twitter_username: xorrior
github_username:  xorrior

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
