title:              Smart Circular Constrution Ecosystems
email:              y.yu-1@utwente.nl
description:        Theories of designing a circularity information platform
author:             Yifei Yu
baseurl:            "/SCCE"
url:                "https://yifei-yu-utwente.github.io" 

# Social Profiles
twitter_username:   
github_username:    Yifei-Yu-UTwente
facebook_username:  Yifei Yu
instagram_username: Yifei Yu 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

