title:             Hsuan-lin Her
email:             b101102109@tmu.edu.tw
description:       Molecules, Sequences, Diseases.
author:            Hsuan-lin Her
baseurl:           ""
url:               "http://algaebrown.github.io"

# Social Profiles
twitter_username:  hermuba
github_username:   algaebrown
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
