title: Danza Kids Blog
email: info@danzakids.com
description: Danza Kids tu espacio de diversion y aprendizaje
author: Danza Kids
baseurl: "/danzakids-blog-jekyll"
url: "http://jjuarez.github.io"

# Social Profiles
twitter_username: danza_kids
facebook_username: DanzaKids

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
