title: Ashutosh Kushwaha
email: akushwaha9808@gmail.com
description: Data Scientist | IIT Bombay
previous_companies: HDFC Life | Flytxt
author: Ashutosh Kushwaha
baseurl: "" #empty
url: "https://ashkush.github.io"

# Social Profiles

github_username: "ashkush"
medium_username: "ashkush"
linkedin_username: "ashkush"

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
