# Site settings
title: Will Green
header-img: img/home-bg.jpg
email: will@willgreen.net
description: "Pirate, Philosopher, Storyteller"
baseurl: ""
url: "https://WILLGREEN.net"
twitter_username: williamgreen
github_username:  aesopist
facebook_username:  #

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
