title:              Chloe Meuse
email:              chloe@taggermedia.com
description:        A Page About Me
author:             Chloe Meuse
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
github_username:    cmeuse
facebook_username:  chloemeuse
instagram_username:  chloemeuse
linkedin_username: chloe-meuse

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
