title:              ismael farah Blog
email:              asmael.net.sy@gmail.com
description:        A Ubuntu Blog
author:             Ismael Farah
baseurl:            ""
url:                "https://ismael.github.io"

# Social Profiles
twitter_username:   ismael_farah1
github_username:    ismaelfarah88
facebook_username:  IsmaelFarah88
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
