title: MIP-Frontiers
email: mip-frontiers@upf.edu
description: New Frontiers in Music Information Processing
author: MIP-Frontiers
url: "https://mip-frontiers.eu"

logo:
  normal: "/img/logo.svg"
  inverted: "/img/logo-white.svg"
lfs_prefix: https://github.com/mip-frontiers/resources/raw/master

# Social Profiles
twitter_username: mip_frontiers
github_username: mip-frontiers

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
background_color: "#205cac"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
