title:              Lucas Bensaid
email:              bensaid.lucas@gmail.com
description:        Data science portfolio and blog
author:             Lucas Bensaid
baseurl:            ""
url:                "https://lucasbens.github.io"

# Social Profiles
twitter_username:   
github_username:    lucasbens
facebook_username:  
instagram_username:  
linkedin_username:  lucas-bensaid-898ab8130

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
# paginate:           5
# paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-paginate-multiple


paginate_multiple:
- paginate: 2
  paginate_path: "/portfolio/page:num/"
  sub_dir: "portfolio"
- paginate: 2
  paginate_path: "/blog/page:num/"
  sub_dir: "blog"