title:              Code 4 Canada (C4C) - Cohort 4
email:              jasper.chan@codefor.ca
description:        Welcome to the blog of Team Pixel-Gram! We are a team of digital experts partnered with Measurement Canada (MC) to bring the latest digital tools and digital thinking to transform MC into an innovative leader in digital governance. We will be blogging with exciting updates every two to four weeks, so stay tuned for the latest information!
author:             Team Pixel-Gram
baseurl:            "/pixel-gram.github.io"
url:                "https://pixel-gram.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username: 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-160662711-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
